### ISSUE TITLE
Emojis & German umlaut is displayed as ? in name and received messages

### ISSUE THREAD

**Issue by a000a** [tulir/mautrix-signal#28]
As the description says, German umlaut like `äüöÄÜÖß` is displayed as `?` in name and received messages.
I'm not sure if it happens with other caracters as well

**Comment by a000a** [comment]
I think it's a problem of `signald`.
the byte stream already contains the question marks

**Comment by a000a** [comment]
well, my system `locale.conf` was misconfigured. 

when I ran `locale -a` the output was `POSIX` instead of something like `en_US.UTF-8`

```
echo LANG=en_US.UTF-8 > /etc/locale.conf
```
and restart the system

to make locale changes immediate run `signald` with

```
/bin/bash -c 'unset LANG; source /etc/profile.d/locale.sh; /path/to/signald/build/install/signald/bin/signald'
```

**Comment by emorrp1** [comment]
Thank you for this, I had the same problem with question marks coming through instead of "smart quotes" i.e. apostrophes in things like "don't". Rather than the specifics above, I went with the debian way: `sudo dpkg-reconfigure locales` but still being sure to select the UTF-8 variant to be the new system default.
