### ISSUE TITLE
Add relaybot support

### ISSUE THREAD

**Issue by uumas** [tulir/mautrix-signal#55]
Relaybot support would probably need to be implemented by using a normal signal account with a dedicated phone number like mautrix-whatsapp does.

**Comment by HansJK** [comment]
This is defiantly a must have!

**Comment by floviolleau** [comment]
Hi @tulir,

Thanks for all efforts you put in this project.

Will this enhancement be soon? Because I need to move all my Whatsapp users before the new policy 15th of May 2021.

I'm a bit confused and didn't understood exactly what is double puppeting. I know you wrote tons of documentation [here](https://docs.mau.fi/bridges/general/double-puppeting.html).

What I wanted is to have a similar experience as the Whatsapp bot for the Signal bot. 

Thanks again!

**Comment by werner-maier** [comment]
PUSH  :grinning:

**Comment by oehlrich9** [comment]
This would be an enormous improvement. I try to link a whatsapp and a signal group into one matrix group for a greater interoperability.

**Comment by js-dot** [comment]
For privacy reasons I promote Signal and Matrix as messengers to my friends & family (so they have the choice ;) ).

So this feature would be awesome. But I mean the uses cases are clear, we are just feature begging here.

**Comment by a000a** [comment]
> For privacy reasons I promote Signal and Matrix as messengers to my friends & family (so they have the choice ;) ).
> 
> So this feature would be awesome for mixed groups, etc.. But I mean the uses cases are clear, we are just feature begging here.
> 
> In order to promote the topic: Can someone estimate the required effort?


since @tulir has already implemented it in telegram (with bot) and whatsapp (without bot) one might have a look at these bridges to figure out

**Comment by frederictobiasc** [comment]
Maybe someone who knows something about signal could make a design proposal.
To my understanding, signal does not provide a Bot-API like Telegram. So it seems, the way to go would be similar to the mautrix-whatsapp relay bot.

**Comment by floviolleau** [comment]
@tulir any reasons why closing it?

**Comment by frederictobiasc** [comment]
Check the commit history

**Comment by floviolleau** [comment]
Yeah, saw the PR #100 

Thanks a lot!
