### ISSUE TITLE
Message not showing when send from another liked device

### ISSUE THREAD

**Issue by Jab2870** [tulir/mautrix-signal#88]
Hi, I have signald set up as a linked device. Unfortunately, if I send a
message from a different device, it doesn't show up in matrix. Is this a known
limitation or have I miss configured something?

Thanks in advance

**Comment by Jab2870** [comment]
My appologies, it turns out I had to set up double puppeting.

If anyone comes across this thread, here is the documentation:

https://docs.mau.fi/bridges/general/double-puppeting.html

**Comment by felixx9** [comment]
I do not totally understand the documentation. Maybe it's only because I dont't know ther perspective to look from
'You can replace the Matrix ghost of your remote account with your Matrix account. When you do so, messages that you send from other clients will be sent from your Matrix account instead of the default ghost user.'

- What or who the Matrix ghost? It the "Signal bridge bot"?
- What is "your remote account" and finally
- my Matrix account (that one seems obvious) - but what's the difference?

The double puppeting is something everbody should activate?

**Comment by shukon** [comment]
Not involved, but I'll tell you what I know:

> I do not totally understand the documentation. Maybe it's only because I dont't know ther perspective to look from
> 'You can replace the Matrix ghost of your remote account with your Matrix account. When you do so, messages that you send from other clients will be sent from your Matrix account instead of the default ghost user.'
> 
>     * What or who the Matrix ghost? It the "Signal bridge bot"?

Matrix ghosts are the users that are created by the bridge bot on the matrix side, e.g. `@signalbot_12301823057102307:some.server.org`. They are used, so each Signal-side user gets display username and avatar.

>     * What is "your remote account" and finally

It's your actual signal account. Your own matrix ghost for your signal-account is a matrix account created by the bridge. If you post something in the original signal app, it might be written by your ghost in the corresponding matrix room, because without allowing the bridge to puppet your account, it cannot write in your name. For other bridges (e.g. telegram) it is also used when backfilling chat history, but I don't think that's possible in Signal.

>     * my Matrix account (that one seems obvious) - but what's the difference?

so you have a matrix account, e.g. `@felixx9:some.server.org` and, when there are messages written in signal by your signal-account, they will appear in matrix from another matrix account that the bridge creates - e.g. `@signalbot_12301823057102307:some.server.org`. Every user/account in Signal will get it's own matrix account created by the bridge. That's why the bridge needs to block a whole namespace, e.g. `@signalbot_*` for these users.

> The double puppeting is something everbody should activate?

You should only activate double puppeting if you 1) trust the bridge and 2) trust the admin. With double puppetering, you give the bridge permission to handle your matrix account.

**Comment by felixx9** [comment]
@shukon that's very good explained - thank you!

**Comment by groldo** [comment]
Hi, I am experiancing something similar but I do think I have double-puppeting with the shared secret plugin set up correct:
I am able to send messages from matrix to signal account but not able to get the other way around.

I did deploy matrix with whatsapp, telegram and the signal bot via the great work from here
https://github.com/spantaleev/matrix-docker-ansible-deploy
whatsapp and telegram working fluently.

When sending ```ping-matrix``` to the bot it answers with ```Your Matrix login is working.```.
Im able to link with my signal account via ```link```.

**Comment by sam9032** [comment]
> Hi, I am experiancing something similar but I do think I have double-puppeting with the shared secret plugin set up correct: I am able to send messages from matrix to signal account but not able to get the other way around.
> 
> I did deploy matrix with whatsapp, telegram and the signal bot via the great work from here https://github.com/spantaleev/matrix-docker-ansible-deploy whatsapp and telegram working fluently.
> 
> When sending `ping-matrix` to the bot it answers with `Your Matrix login is working.`. Im able to link with my signal account via `link`.

Hm, same here. Works like a charm for a while but now no way to reactivate the signal bridge where the answers got bridged to matrix.
Do you find anything helpful to solve your problem?

**Comment by sam9032** [comment]
> 

It seems to work with another matrix user and a different signal account. So maybe a double puppeting issue but no clue how to fix it without breaking the existing chats.

**Comment by groldo** [comment]
> > Hi, I am experiancing something similar but I do think I have double-puppeting with the shared secret plugin set up correct: I am able to send messages from matrix to signal account but not able to get the other way around.
> > I did deploy matrix with whatsapp, telegram and the signal bot via the great work from here https://github.com/spantaleev/matrix-docker-ansible-deploy whatsapp and telegram working fluently.
> > When sending `ping-matrix` to the bot it answers with `Your Matrix login is working.`. Im able to link with my signal account via `link`.
> 
> Hm, same here. Works like a charm for a while but now no way to reactivate the signal bridge where the answers got bridged to matrix. Do you find anything helpful to solve your problem?

In my case a simple restart of the service did the trick. \o/
Hope it might be helpful
